# @package _global_

# default debugging setup, runs 1 full epoch
# other debugging configs can inherit from this one

defaults:
  - override /logging: [csv]

task_name: debug

trainer:
  max_epochs: 1
  devices: 1
  accelerator: gpu
  detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor

# sets level of all command line loggers to 'DEBUG'
hydra:
  job_logging:
    root:
      level: DEBUG

  # use this to set level of only chosen command line loggers to 'DEBUG':
  # verbose: True
