# @package _global_

# default debugging setup, runs 1 full epoch
# other debugging configs can inherit from this one

defaults:
  - override /logdir: debug
  - override /logging: [csv]

trainer:
  max_epochs: 1
  devices: 1
  accelerator: gpu
  detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor
  track_grad_norm: 2 # track gradient norm with loggers

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  verbose: True

  # use this to set level of only chosen command line loggers to 'DEBUG':
  # verbose: [src.train, src.utils]
