# @package _global_

# runs with execution time profiling

defaults:
  - default.yaml

trainer:
  max_epochs: 1
  # profiler: "simple"
  # profiler: "advanced"
  # profiler: "pytorch"
  profiler:
    _target_: lightning.pytorch.profilers.PyTorchProfiler
    # emit_nvtx: true
    dirpath: profiling
    filename: pytorch_profiler
    export_to_chrome: true
  detect_anomaly: false # raise exception if NaN or +/-inf is detected in any tensor
