# Using gpus to train the model
accelerator: gpu
devices: 1
strategy: ddp
sync_batchnorm: True
deterministic: true

precision: 32
accumulate_grad_batches: 1

profiler: simple
weights_summary: top

max_epochs: 10
val_check_interval: 0.5

default_root_dir: ./
