checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint

  dirpath: ${paths.output_dir}/checkpoints
  filename: "{epoch:03d}-{step}"
  save_last: true

  monitor: "val/acc"
  mode: "max"
  save_top_k: 1

  verbose: true
