# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

run:
  dir: /log/${task_name}/${oc.env:PROJECT}/${exp_id}
sweep:
  dir: /log/${task_name}/${oc.env:PROJECT}/sweep_${exp_id}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${paths.output_dir}/train.log

job:
  chdir: True